### ISSUE TITLE
What does function compress_whnp in convert_questions.py do?

### ISSUE THREAD

**Issue by ghost** [robinjia/adversarial-squad#2]
Hi.
I am a NLP beginner. I am not familiar with traditional NLP method, so I can't fully understand function of compress_whnp. Can you give me a detailed explanation of this function? Thanks!

**Comment by robinjia** [comment]
To the best of my recollection, the point of that function was to deal with things like "What English actor was born in 1942?"  Here, "What English actor" is a WHNP (wh-word noun phrase).  For some downstream things, I wanted the WHNP to be further broken down into two constituents, "What" and "English actor".  However, instead the parse usually just has "What", "English" and "actor" as three separate children.  So the compress_whnp function will merge "English" and "actor" into a single NP.

I'm not actually mattered in the final version, since I wound up basically ignoring everything in the WHNP that wasn't the question word.
